// Known-benign CSP violations that are dropped before they reach KV.
//
// Why this exists: the collector was receiving ~500 reports/day, essentially
// all of them one host, which buried real violations. On 2026-08-31 a check
// for PostHog violations came back "clean" only because 985 identical
// doubleclick reports had pushed everything else out of reach.
//
// The bar for adding a host here is high: it must be VERIFIED benign, with
// the evidence written down. A host that is merely noisy stays.

export const IGNORED_HOSTS = new Set([
  // Generated by our OWN GA4 tag, not a third party and not an extension.
  // Verified 2026-08-31 across 985 reports: every one carried tid=G-9YM9ZDW1J9
  // across 754 distinct cids and ordinary browsers. The trigger is npa=0
  // (ad personalization on); the same URLs carry ngs=1, and the GA4 Admin API
  // confirms googleSignalsSettings = GOOGLE_SIGNALS_DISABLED, so Google
  // Signals is NOT the cause. Nothing in the site references doubleclick —
  // gtag.js reaches the ads endpoint on its own. Blocking it is correct and
  // intended, so the report carries no information we act on.
  "stats.g.doubleclick.net",
]);

// NOTE: connect.facebook.net is deliberately NOT in this list. It was long
// assumed to be extension injection, but that was never verified the way the
// doubleclick case now has been. Leave it reporting until someone checks.

/**
 * True if this report should be dropped instead of written to KV.
 *
 * Only understands the `report-uri` payload shape (`{"csp-report": {...}}`),
 * which is the only shape we receive: site/src/_headers.njk uses `report-uri`,
 * not the newer `report-to`. Anything unrecognised returns false, so an
 * unexpected shape is stored rather than silently discarded.
 */
export function shouldIgnoreReport(parsed) {
  const blocked = parsed?.["csp-report"]?.["blocked-uri"];
  if (typeof blocked !== "string" || blocked === "") return false;

  let host;
  try {
    host = new URL(blocked).hostname;
  } catch {
    return false; // "eval", "inline", "data", or junk — keep it
  }
  return IGNORED_HOSTS.has(host);
}
